### ISSUE TITLE
OPeNDAP backend for harp_import

### ISSUE THREAD

**Issue by StevenCompernolle** [stcorp/harp#175]
It would be useful if the matlab interface "harp_import" command is extended to cover also opendap url's, in analogy to matlab's "ncread" command.

**Comment by svniemeijer** [comment]
This is definitely an interesting idea.

If we implement an opendap reading interface for harp_import than this will be at the C library level and would then benefit all interfaces (C, Python, IDL, MATLAB).

We will have to see how much extra code we need to pull in to get this to work.
It will likely become on optional build setting to enable this, just like the MATLAB and IDL interfaces.

**Comment by svniemeijer** [comment]
Introducing an opendap interface for HARP data also requires that we specify how HARP data is served via opendap, since variables can be represented in different ways.
For instance the default netcdf handler of the pypdap server wraps all variables in a GridType for all variables, but for the HARP opendap interface we want variables as plain BaseType data. This latter approach is also what is currently implemented in the S5P MPC Validation Server, so that can serve as a reference.

**Comment by svniemeijer** [comment]
Closed, as we don't see this as a future feature of HARP anymore.
Even if it might still be an interesting idea, it is probably best handled using an independent software component (i.e. some pure python module that fetches data via opendap and returns a harp.Product instance).
