### ISSUE TITLE
Add support for 'scene' quantities (pressure, albedo, type)

### ISSUE THREAD

**Issue by svniemeijer** [stcorp/harp#178]
We need to find a proper variable name for quantities like effective scene pressure, effective scene albedo and scene type.

This impacts the CCI and S5P L2 O3 products (scene pressure + albedo) and the GOMOS products (illumination condition is currently captured by a scene type).

**Comment by StevenCompernolle** [comment]
Also for S5P NO2 one has scene pressure + scene albedo. This is from a fallback algorithm, the LER method. Because the default algorithm cannot distinguish between surface and cloud for high surface albedo (snow and ice).
Jos van Geffen recommended following article https://www.atmos-meas-tech.net/9/6035/2016/amt-9-6035-2016.pdf to understand what it means. Important sentence in section 2.2.1:  "the LER method does not need to distinguish between the cloud and the surface, as it only ﬁts the scene albedo and
the scene pressure."

**Comment by svniemeijer** [comment]
Implemented in 8d3f31190a29627eccacc4a0cee77e5af5c280fb, 55832a3937973178595976d311eeef67396619b0, and 123894e8bfdd02cc87e6420e519d42b6d09bcdb9
