### ISSUE TITLE
Prevent NaNs from being generated in S5P latitude and longitude variables

### ISSUE THREAD

**Issue by WodahsReklaw** [stcorp/harp#189]
When converting the Sentinel 5P OFFL L2 CLOUD product to L3:
`S5P_OFFL_L2__CLOUD__20180805T133256_20180805T151426_04202_01_010102_20180811T125922`

e.g. 
```
./harpconvert --format hdf5 --hdf5-compression 9 S5P_OFFL_L2__CLOUD__20180805T133256_20180805T151426_04202_01_010102_20180811T125922.nc cloud_offl_nan.h5
```

The resulting data appears to have numerous nan values in the "latitude" and "longitude" variables.  Out of all the S5P data I have converted to L3 (thousands of products) this is the first time I have encountered this issue.  The source product itself seems to contain valid data and contains no NaNs in the source "latitude" and "longitude" variables.

It may be useful for harpconvert to fail converting the data if there truly is an issue, otherwise it may be desirable to drop the nan lat/lons altogether while processing the data.

**Comment by svniemeijer** [comment]
The product that you mention seems to have problems. The pixels where latitude and longitude end up as NaN have 'fill values' in the product. The behaviour of HARP is to map all fill values (that are outside the valid_min/valid_max range) of floating point values to NaN. So the behaviour is as expected.

You can see that the product has fill values yourself by using e.g. `ncdump -v /PRODUCT/latitude S5P_OFFL_L2__CLOUD__20180805T133256_20180805T151426_04202_01_010102_20180811T125922.nc`
It seems that rows 4-13 and 18 (0-based) are affected.
Note that the product does not contain a full orbit. It seems that the CO and NO2 product for the same orbit have the same problem. So it is likely an acquisition/L0 problem.
However, where the CO and NO2 products just omit those rows in the products, the CLOUD product seems to contain these rows with fill values.
This is therefore something you will have to raise with Copernicus/ESA.

In general you should only include measurements for which the qa_value matches what the product [README](http://www.tropomi.eu/sites/default/files/files/S5P-MPC-DLR-PRF-CLOUD_v01.00.00_1.0.0_20180709_signed.pdf) mentions.
For the CLOUD product this qa_value can be found as `cloud_fraction_validity` in HARP which contains the unscaled qa_value that ranges from 0 to 100. So you should use something like `harpconvert -a 'cloud_fraction_validity>50' S5P_OFFL_L2__CLOUD__20180805T133256_20180805T151426_04202_01_010102_20180811T125922.nc output.nc`
Interestingly enough this filtering does not seem to exclude the pixels with lat/lon fill values (those pixels all seem to have a qa_value of 100 (1.0)). So this is something else to raise with Copernicus/ESA (since those pixels should have a qa_value of 0).

Finally, be aware that a straight harpconvert is not a L3 conversion (the output data is still L2). Only if you perform a `bin_spatial` operation will you convert the data to L3.

**Comment by svniemeijer** [comment]
Thanks for the clarifications.

Closing the issue since there is nothing to be performed for HARP.

**Comment by simonff** [comment]
Why not fail with an error when such an invalid product is detected?

**Comment by svniemeijer** [comment]
Because from the perspective of HARP there is nothing wrong with the product. And HARP is also not a QC tool.
If you want to filter out bad products, you will have to do this using separate tools before calling HARP.
