### ISSUE TITLE
Derive pressure, pressure_bounds from ECMWF grib if only surface_pressure and a,b coefficients available

### ISSUE THREAD

**Issue by StevenCompernolle** [stcorp/harp#209]
Currently there is the condition for ECMWF grib ingestion, for pressure and pressure_bounds variables that
"surface_pressure is available and at least one parameter has vertical coordinate values"
surface_pressure is necessary input, as are the ECMWF hybrid a,b coefficients.
But why the condition of having another parameter with vertical coordinate values?

Unfortunately, ECMWF grib files are stored at our place as one separate file per variable. So the lnsp variable is stored without a parameter with vertical coordinate values and upon harp ingestion, no pressure or pressure_bounds can be derived.

**Comment by svniemeijer** [comment]
This was a design choice since we did not expect users to want to use GRIB files with _only_ pressure information.

In GRIB, the vertical pressure profile is not considered a 'parameter', but annotation information _of_ a parameter. This is also how HARP currently deals with the pressure vertical coordinate in the ingestions. We only calculate the vertical pressure when it is needed as a coordinate variable of an actual _parameter_ that is provided at vertical levels.

Furthermore, we only provide the pressure vertical levels for the levels for which there are GRIB messages in the GRIB file (note that each level of a parameter that has a vertical coordinate is stored as a separate GRIB message). This allows you to e.g. only retrieve the bottom 10 levels of the 135 levels and HARP will then create a vertical grid with only those bottom 10 levels. However, knowing which levels to provide requires at least one parameter that has vertical coordinates.

I currently don't see a good way of still adding the full pressure grid without breaking the above.

Note also that it is quite easy to combine GRIB files if you have them stored separately. You can just do a binary concatenation. And you can then ingest this concatenated file in HARP.
