### ISSUE TITLE
Finalize support for S5P

### ISSUE THREAD

**Issue by svniemeijer** [stcorp/harp#66]
Ingestion modules need to be implemented for the following S5P L2 product types:
- [x] Tropospheric O3 total column (L2__O3_TCL)
- [x] Aerosol layer heigth (L2__AER_LH)

The layer height information contained in L2__AER_LH products is mapped to 'altitude' and 'pressure' HARP variables.

There is also an UV  product (surface irradiance and erythemal dose, _not_ the same as the UV aerosol index L2__AER_AI product) produced by the Finnish collaborative ground segment. See the [list of Level 2 products](http://www.tropomi.eu/science/level-2-products). Currently, there is no ingestion module for this product type. No product specification nor sample products seem to be available.

Other open issues:
- L2: The unit of the time variable could be dynamic, as mentioned in the L2 product specification. If so, the implementation needs to be changed, since at the moment the unit of the time variable is assumed to be "seconds since 2010-01-01". We currently keep assuming a static value.
- [x] Add pressure / altitude variables for products that do not contain this information, if possible. In some cases, there seems to be other information (polynomial coefficients) available in the product that may allow these values to be computed. (See for example the L2__NO2___ product, variable "pressure_levels".)
- [x] L2__CH4___: Add ingestion option to allow the user to choose between XCH4 and XCH4_bias_corrected.
- [x] L2__SO2___: By default `PRODUCT.so2_vertical_column` and `PRODUCT.SUPPORT_DATA.DETAILED_RESULTS.amf_total_polluted` (no volcanic eruption scenario) should be ingested. For volcanic eruption scenarios we should allow the user to ingest `PRODUCT.SUPPORT_DATA.DETAILED_RESULTS.so2_vertical_column_15km` (+ `7km` + `1km`) and `PRODUCT.SUPPORT_DATA.DETAILED_RESULTS.amf_total_15km` (+ ...) as well (via an ingestion option)

**Comment by svniemeijer** [comment]
Explanations received for the NO2 product from the algorithm developer:

 - 'surface_albedo_no2' and 'cloud_fraction_no2' are obtained at the correct visible wavelength (VIS) of the NO2 retrieval, while 'surface_albedo' and 'cloud_fraction' are obtained at near-infrared (NIR). 'cloud_pressure' is also obtained at NIR. It is not possible to obtain cloud_pressure at VIS.
Also, there is a field-of-view misalignment between the NIR retrieved 'cloud_fraction' and the VIS NO2 retrieval. Finally, 'surface_albedo_no2' is from a higher resolution OMI database compared to 'surface_albedo', with a better land/ocean transition. This means thatHARP should ingest 'surface_albedo_no2', 'cloud_fraction_no2', and 'cloud_pressure' as the default for these quantities  (and 'surface_albedo' or 'cloud_fraction' as potential alternatives).

 - In the case of snow/ice (as determined by the snow/ice flag), a user can decide not to use cloud pressure and cloud fraction (which can become unreliable), but rather to use 'scene_albedo' and 'scene_pressure' instead. These quantities are derived from other model assumptions than cloud pressure and cloud fraction. 'scene_pressure' can be close to surface pressure, but not necessarily. It is TBD whether HARP should ingest 'scene_albedo' and 'scene_pressure', but if it does, there should be separate HARP names for it (as it is in general not equal to surface albedo or surface pressure or cloud albedo or cloud pressure).

 - For the choice between summed_no2_total_vertical_column and total_no2_vertical_column, summed_no2_total_vertical_column is the best estimate, while total_no2_vertical_column is useful for data assimilation.

**Comment by 0xA000** [comment]
Open issues for S5P L1B products:
- [ ] Determine how to map uncertainty information to HARP.
- [ ] Check difference in Avogadro's number between HARP and L1B product specification.

**Comment by 0xA000** [comment]
Open issues for S5P L2 products:

At the moment, there are no ingestion modules for the following S5P L2 product types:
- [ ] Tropospheric O3 products (L2__O3_TPR and L2__O3_TCL).
- [ ] Aerosol layer heigth (L2__AER_LH).
- [ ] UV (*not* UV aerosol index L2__AER_AI)

The L2__O3_TCL product seems to be an imaging product (using a fixed latitude, longitude grid). The format of L2__O3_TPR products seems to be identical to that of L2__O3_PR products, but no L2__O3_TPR sample products are available. It is currently unclear how to map the information contained in L2__AER_LH products to HARP variables. For the UV (surface irradiance, erythemal dose) product, no product specification nor sample products are available.

Other open issues:
- [ ] Check whether the unit of the time variable is truly dynamic, as mentioned in the L2 product specification. If so, the implementation needs to be changed, since at the moment the unit of the time variable is assumed to be "seconds since 2010-01-01".
- [ ] Determine how to map uncertainty information to HARP.
- [ ] Determine how to compute pressure / altitude for products that do not contain this information. In some cases, it seems there is other information (polynomial coefficients) available in the product that may allow these values to be computed? (See for example the L2__NO2___ product, variable "pressure_levels".)
- [ ] L2__CH4___: Is the mapping from XCH4 (see  product format specification) to CH4_column_volume_mixing_ratio correct?
- [ ] L2__CH4___: Add ingestion option to allow the user to choose between XCH4 and XCH4_bias_corrected. Check whether XCH4_precision applies to both, or only the XCH4 and adjust the implementation accordingly.
- [ ] Determine if, and if so which, additional variables need to be added.
